#+title: Petya And Strings

Little Petya loves presents. His mum bought him two strings of the same size for his birthday. The strings consist of uppercase and lowercase Latin letters. Now Petya wants to compare those two strings lexicographically. The letters' case does not matter, that is an uppercase letter is considered equivalent to the corresponding lowercase letter. Help Petya perform the comparison.

*Input*

Each of the first two lines contains a bought string. The strings' lengths range from 1 to 100 inclusive. It is guaranteed that the strings are of the same length and also consist of uppercase and lowercase Latin letters.

*Output*

If the first string is less than the second one, print "-1". If the second string is less than the first one, print "1". If the strings are equal, print "0". Note that the letters' case is not taken into consideration when the strings are compared.

*Examples*

*Input*

#+begin_src txt
aaaa
aaaA
#+end_src

*Output*

#+begin_src txt
0
#+end_src

*Input*

#+begin_src txt
abs
Abz
#+end_src

*Output*

#+begin_src txt
-1
#+end_src

*Input*

#+begin_src txt
abcdefg
AbCdEfF
#+end_src

*Output*

#+begin_src txt
1
#+end_src


*CPP CODE*

#+BEGIN_SRC CPP
#include <bits/stdc++.h>
using namespace std;

void solve() {
  string s1, s2;
  cin >> s1 >> s2;
  transform(s1.begin(), s1.end(), s1.begin(), ::tolower);
  transform(s2.begin(), s2.end(), s2.begin(), ::tolower);
  if (s1 > s2)
    cout << "1"
         << "\n";
  else if (s1 == s2)
    cout << "0"
         << "\n";
  else
    cout << "-1"
         << "\n";
}

int main() {
  int t = 1;
  // cin >> t;
  while (t--) {
    solve();
  }
  return 0;
}
#+END_SRC
