#+title: Marks

Vasya, or Mr. Vasily Petrov is a dean of a department in a local university. After the winter exams he got his hands on a group's gradebook.

Overall the group has n students. They received marks for m subjects. Each student got a mark from 1 to 9 (inclusive) for each subject.

Let's consider a student the best at some subject, if there is no student who got a higher mark for this subject. Let's consider a student successful, if there exists a subject he is the best at.

Your task is to find the number of successful students in the group.

*Input*

The first input line contains two integers n and m (1 ≤ n, m ≤ 100) — the number of students and the number of subjects, correspondingly. Next n lines each containing m characters describe the gradebook. Each character in the gradebook is a number from 1 to 9. Note that the marks in a rows are not sepatated by spaces.

*Output*

Print the single number — the number of successful students in the given group.

*Examples*

*Input*

#+begin_src txt
3 3
223
232
112
#+end_src

*Output*

#+begin_src txt
2
#+end_src

*Input*

#+begin_src txt
3 5
91728
11828
11111
#+end_src

*Output*

#+begin_src txt
3
#+end_src

#+begin_quote
*Note*

In the first sample test the student number 1 is the best at subjects 1 and 3, student 2 is the best at subjects 1 and 2, but student 3 isn't the best at any subject.

In the second sample test each student is the best at at least one subject.
#+end_quote


*CPP CODE*

#+BEGIN_SRC C++
#include <bits/stdc++.h>
using namespace std;

int main() {
  size_t n, m;
  cin >> n >> m;
  vector<string> marks(n);
  for (size_t i = 0; i < n; ++i) {
    cin >> marks[i];
  }
  vector<bool> successful(n, false);
  for (size_t subject = 0; subject < m; ++subject) {
    char best = '0';
    for (size_t i = 0; i < n; ++i) {
      if (marks[i][subject] > best) {
        best = marks[i][subject];
      }
    }
    for (size_t i = 0; i < n; ++i) {
      if (marks[i][subject] == best) {
        successful[i] = true;
      }
    }
  }
  cout << count(successful.begin(), successful.end(), true);
  return 0;
}
#+END_SRC
