#+title: Comparing Strings

Some dwarves that are finishing the StUDY (State University for Dwarven Youngsters) Bachelor courses, have been told "no genome, no degree". That means that all dwarves should write a thesis on genome. Dwarven genome is far from simple. It is represented by a string that consists of lowercase Latin letters.

Dwarf Misha has already chosen the subject for his thesis: determining by two dwarven genomes, whether they belong to the same race. Two dwarves belong to the same race if we can swap two characters in the first dwarf's genome and get the second dwarf's genome as a result. Help Dwarf Misha and find out whether two gnomes belong to the same race or not.

*Input*

The first line contains the first dwarf's genome: a non-empty string, consisting of lowercase Latin letters.

The second line contains the second dwarf's genome: a non-empty string, consisting of lowercase Latin letters.

The number of letters in each genome doesn't exceed 10^5. It is guaranteed that the strings that correspond to the genomes are different. The given genomes may have different length.

*Output*

Print "YES", if the dwarves belong to the same race. Otherwise, print "NO".

*Examples*

*Input*

#+begin_src txt
ab
ba

aa
ab
#+end_src

*Output*

#+begin_src txt
YES

NO
#+end_src

#+begin_quote
*Note*

+ First example: you can simply swap two letters in string "ab". So we get "ba".
+ Second example: we can't change string "aa" into string "ab", because "aa" does not contain letter "b".
#+end_quote


*CPP CODE*

#+BEGIN_SRC C++
#include <bits/stdc++.h>
using namespace std;

int main() {
  char s1[100005], s2[100005], a[2], b[2];
  int l1, l2, i, j = 0, cnt = 0;
  cin >> s1 >> s2;
  l1 = strlen(s1);
  l2 = strlen(s2);
  if (l1 != l2) {
    cout << "NO" << endl;
    return 0;
  } else {
    for (i = 0; i < l1; i++) {
      if (s1[i] != s2[i]) {
        cnt++;
        a[j] = s1[i];
        b[j] = s2[i];
        j++;
        if (cnt > 2) {
          cout << "NO" << endl;
          return 0;
        }
      }
    }
  }
  if (a[1] == b[0] && a[0] == b[1]) {
    cout << "YES" << endl;
  } else {
    cout << "NO" << endl;
  }

  return 0;
}
#+END_SRC
