#+title: Roma and Lucky Numbers

Roma (a popular Russian name that means 'Roman') loves the Little Lvov Elephant's lucky numbers.

Let us remind you that lucky numbers are positive integers whose decimal representation only contains lucky digits 4 and 7. For example, numbers 47, 744, 4 are lucky and 5, 17, 467 are not.

Roma's got n positive integers. He wonders, how many of those integers have not more than k lucky digits? Help him, write the program that solves the problem.

*Input*

The first line contains two integers n, k (1 ≤ n, k ≤ 100). The second line contains n integers ai (1 ≤ ai ≤ 10^9) — the numbers that Roma has.

The numbers in the lines are separated by single spaces.

*Output*

In a single line print a single integer — the answer to the problem.

*Examples*

*Input* 

#+begin_src txt
3 4
1 2 4
#+end_src

*Output*

#+begin_src txt
3
#+end_src

*Input*

#+begin_src txt
3 2
447 44 77
#+end_src

*Output*

#+begin_src txt
2
#+end_src

#+begin_quote
*Note*

In the first sample all numbers contain at most four lucky digits, so the answer is 3.

In the second sample number 447 doesn't fit in, as it contains more than two lucky digits. All other numbers are fine, so the answer is 2.
#+end_quote


*CPP CODE*

#+BEGIN_SRC C++
#include <iostream>
#include <string>
using namespace std;

int main() {
  int n, k, count(0);
  cin >> n >> k;

  string s;
  while (n--) {
    int lucky(0);
    cin >> s;
    for (size_t i = 0; i < s.length(); ++i) {
      if (s[i] == '4' || s[i] == '7') {
        lucky += 1;
      }
    }
    if (lucky <= k) {
      count += 1;
    }
  }
  cout << count << endl;
  return 0;
}
#+END_SRC
