#+title: Collecting Beats is Fun

Cucumber boy is fan of Kyubeat, a famous music game.

Kyubeat has 16 panels for playing arranged in 4 × 4 table. When a panel lights up, he has to press that panel.

Each panel has a timing to press (the preffered time when a player should press it), and Cucumber boy is able to press at most k panels in a time with his one hand. Cucumber boy is trying to press all panels in perfect timing, that is he wants to press each panel exactly in its preffered time. If he cannot press the panels with his two hands in perfect timing, his challenge to press all the panels in perfect timing will fail.

You are given one scene of Kyubeat's panel from the music Cucumber boy is trying. Tell him is he able to press all the panels in perfect timing.

*Input*

The first line contains a single integer k (1 ≤ k ≤ 5) — the number of panels Cucumber boy can press with his one hand.

Next 4 lines contain 4 characters each (digits from 1 to 9, or period) — table of panels. If a digit i was written on the panel, it means the boy has to press that panel in time i. If period was written on the panel, he doesn't have to press that panel.

*Output*

Output "YES" (without quotes), if he is able to press all the panels in perfect timing. If not, output "NO" (without quotes).

*Examples*

*Input*

#+begin_src txt
1
.135
1247
3468
5789
#+end_src

*Output*

#+begin_src txt
YES
#+end_src

*Input*

#+begin_src txt
5
..1.
1111
..1.
..1.
#+end_src

*Output*

#+begin_src txt
YES
#+end_src

*Input*

#+begin_src txt
1
....
12.1
.2..
.2..
#+end_src

*Output*

#+begin_src txt
NO
#+end_src

#+begin_quote
*Note*

In the third sample boy cannot press all panels in perfect timing. He can press all the panels in timing in time 1, but he cannot press the panels in time 2 in timing with his two hands.
#+end_quote


*CPP CODE*

#+BEGIN_SRC C++
#include <bits/stdc++.h>
using namespace std;

int main() {
  int k, i, j, maxi = 0, b;
  cin >> k;
  int total[10];
  for (i = 1; i <= 9; i++) {
    total[i] = 0;
  }
  string a[4];
  for (i = 0; i < 4; i++) {
    cin >> a[i];
    for (j = 0; j < 4; j++) {
      b = atoi(a[i].substr(j, 1).c_str());
      total[b]++;
      if (b > maxi) {
        maxi = b;
      }
    }
  }
  for (i = 1; i <= maxi; i++) {
    if (total[i] > (2 * k)) {
      cout << "NO";
      exit(0);
    }
  }
  cout << "YES";
  return 0;
}
#+END_SRC
