#+title: The Child and Homework

Once upon a time a child got a test consisting of multiple-choice questions as homework. A multiple-choice question consists of four choices: A, B, C and D. Each choice has a description, and the child should find out the only one that is correct.

Fortunately the child knows how to solve such complicated test. The child will follow the algorithm:

  + If there is some choice whose description at least twice shorter than all other descriptions, or at least twice longer than all other descriptions, then the child thinks the choice is great.
  + If there is exactly one great choice then the child chooses it. Otherwise the child chooses C (the child think it is the luckiest choice).

You are given a multiple-choice questions, can you predict child's choose?

*Input*

The first line starts with "A." (without quotes), then followed the description of choice A. The next three lines contains the descriptions of the other choices in the same format. They are given in order: B, C, D. Please note, that the description goes after prefix "X.", so the prefix mustn't be counted in description's length.

Each description is non-empty and consists of at most 100 characters. Each character can be either uppercase English letter or lowercase English letter, or "_".

*Output*

Print a single line with the child's choice: "A", "B", "C" or "D" (without quotes).

*Examples*

*Input*

#+begin_src txt
A.VFleaKing_is_the_author_of_this_problem
B.Picks_is_the_author_of_this_problem
C.Picking_is_the_author_of_this_problem
D.Ftiasch_is_cute
#+end_src

*Output*

#+begin_src txt
D
#+end_src

Input*

#+begin_src txt
A.ab
B.abcde
C.ab
D.abc
#+end_src

*Output*

#+begin_src txt
C
#+end_src

Input*

#+begin_src txt
A.c
B.cc
C.c
D.c
#+end_src

*Output*

#+begin_src txt
B
#+end_src

#+begin_quote
*Note*

In the first sample, the first choice has length 39, the second one has length 35, the third one has length 37, and the last one has length 15. The choice D (length 15) is twice shorter than all other choices', so it is great choice. There is no other great choices so the child will choose D.

In the second sample, no choice is great, so the child will choose the luckiest choice C.

In the third sample, the choice B (length 2) is twice longer than all other choices', so it is great choice. There is no other great choices so the child will choose B.
#+end_quote


*CPP CODE*

#+BEGIN_SRC C++
#pragma GCC optimize("O3")
#include <bits/stdc++.h>
#define loop(i, a, b) for (ll i = a; i <= b; ++i)
#define boost ios_base::sync_with_stdio(0);
#define eb emplace_back
#define itoc(c) ((char)(((int)'0') + c))
#define ctoi(c) ((int)(((int)c) - '0'))
#define all(p) p.begin(), p.end()

using ll = long long int;
using namespace std;
using vec = vector<int>;

int main() {
  string s;
  vec v(4);

  for (int i = 0; i < 4; i++) {
    cin >> s;
    v[i] = s.size() - 2;
  }

  bool a = false, b = false;
  int ind = -1;
  string choice = "ABCD";

  int cnt = 0;
  for (int i = 0; i < 4; i++) {
    a = true, b = true;
    for (int j = 0; j < 4; j++) {
      if (i == j)
        continue;
      if (v[j] * 2 > v[i])
        a = false;
      if (v[j] < v[i] * 2)
        b = false;
    }
    if (a ^ b) {
      ind = i;
      cnt++;
    }
  }

  if (cnt == 1)
    printf("%c\n", char(choice[ind]));
  else
    puts("C");

  return 0;
}
#+END_SRC
