#+title: Valera and Antique Items

Valera is a collector. Once he wanted to expand his collection with exactly one antique item.

Valera knows n sellers of antiques, the i-th of them auctioned ki items. Currently the auction price of the j-th object of the i-th seller is sij. Valera gets on well with each of the n sellers. He is perfectly sure that if he outbids the current price of one of the items in the auction (in other words, offers the seller the money that is strictly greater than the current price of the item at the auction), the seller of the object will immediately sign a contract with him.

Unfortunately, Valera has only v units of money. Help him to determine which of the n sellers he can make a deal with.

*Input* 

The first line contains two space-separated integers n, v (1 ≤ n ≤ 50; 10^4 ≤ v ≤ 10^6) — the number of sellers and the units of money the Valera has.

Then n lines follow. The i-th line first contains integer ki (1 ≤ ki ≤ 50) the number of items of the i-th seller. Then go ki space-separated integers si1, si2, ..., siki (10^4 ≤ sij ≤ 10^6) — the current prices of the items of the i-th seller.

*Output*

In the first line, print integer p — the number of sellers with who Valera can make a deal.

In the second line print p space-separated integers q1, q2, ..., qp (1 ≤ qi ≤ n) — the numbers of the sellers with who Valera can make a deal. Print the numbers of the sellers *in the increasing order*.

*Examples*

*Input*

#+begin_src txt
3 50000
1 40000
2 20000 60000
3 10000 70000 190000
#+end_src

*Output*

#+begin_src txt
3
1 2 3
#+end_src

*Input*

#+begin_src txt
3 50000
1 50000
3 100000 120000 110000
3 120000 110000 120000
#+end_src

*Output*

#+begin_src txt
0
#+end_src

*CPP CODE*

#+BEGIN_SRC C++
#include <algorithm>
#include <bits/stdc++.h>
#include <string>
using namespace std;

int main() {
  int n, v;
  cin >> n >> v;
  set<int> ans;
  for (int i = 0; i < n; ++i) {
    int k;
    cin >> k;
    for (int j = 0; j < k; ++j) {
      int a;
      cin >> a;
      if (v > a) {
        ans.insert(i + 1);
      }
    }
  }
  if (ans.size() > 0) {
    cout << ans.size() << "\n";
    for (auto it : ans)
      cout << it << " ";
    cout << "\n";
  } else
    cout << 0 << "\n";
  return 0;
}
#+END_SRC
